# Generated by scripts/konsole-profiles.sh. Edits here are lost on the next run.
[Appearance]
ColorScheme=Halo
Font=Hack,11,-1,5,50,0,0,0,0,0

[General]
Name=Halo
Parent=FALLBACK/
TerminalColumns=110
TerminalRows=32

[Scrolling]
HistoryMode=2
ScrollFullPage=1

[Terminal Features]
BellMode=0
BlinkingCursorEnabled=true
